language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/9c602f881f2b55649011e37002f9177cbf9af8b2/.travis-docker.sh
script: bash -ex .travis-docker.sh
sudo: required
services:
  - docker
sudo: false
env:
 global:
   - PRE_INSTALL_HOOK="cd /home/opam/opam-repository && git pull origin master && opam update -u -y"
   - POST_INSTALL_HOOK="sh ./.travis-ci.sh"
   - PINS="mirage.dev:. mirage-types.dev:. mirage-types-lwt.dev:. mirage-runtime.dev:."
   - EXTRA_REMOTES="https://github.com/mirage/mirage-dev.git"
 matrix:
   - PACKAGE=mirage DISTRO=debian-testing OCAML_VERSION=4.04 EXTRA_ENV="MODE=xen"
   - PACKAGE=mirage DISTRO=debian-testing OCAML_VERSION=4.04 EXTRA_ENV="MODE=hvt"
   - PACKAGE=mirage DISTRO=debian-unstable OCAML_VERSION=4.04 EXTRA_ENV="MODE=unix"
   - PACKAGE=mirage DISTRO=ubuntu-16.04 OCAML_VERSION=4.05 EXTRA_ENV="MODE=xen"
   - PACKAGE=mirage DISTRO=ubuntu-16.04 OCAML_VERSION=4.05 EXTRA_ENV="MODE=hvt"
   - PACKAGE=mirage DISTRO=ubuntu-16.04 OCAML_VERSION=4.05 EXTRA_ENV="MODE=virtio"
   - PACKAGE=mirage DISTRO=debian-testing OCAML_VERSION=4.06 EXTRA_ENV="MODE=unix"
   - PACKAGE=mirage DISTRO=debian-testing OCAML_VERSION=4.06 EXTRA_ENV="MODE=hvt"
   - PACKAGE=mirage DISTRO=debian-testing OCAML_VERSION=4.06 EXTRA_ENV="MODE=muen"
